name: git-action-tutorial

on:
  push:

jobs:
  pika-git-action-basic-test:
    runs-on: ubuntu-latest

    steps:
      - name: step1 저장소 코드 가져오기
        uses: actions/checkout@v4

      - name: step2 Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: step3 pytest 설치
        run: pip install pytest

      - name: step4 CI 기본 테스트 실행
        run: pytest test_basic_ci.py
